services:
  db:
    image: postgres:16
    container_name: assemblee-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-assemblee}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-assemblee} -U ${POSTGRES_USER:-user} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  pg_data:
