version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s %(levelname)s [%(name)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn.error:
    level: DEBUG
    handlers: [console]
    propagate: false
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: false
  src:                 
    level: DEBUG
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]
