"""init jsonb tables

Revision ID: 05231df2c956
Revises: 
Create Date: 2025-09-30 22:13:02.163988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05231df2c956'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acteur',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('document',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('organe',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###

    # Index GIN génériques sur JSONB
    op.create_index("ix_acteur_payload_gin", "acteur", ["payload"], postgresql_using="gin")
    op.create_index("ix_organe_payload_gin", "organe", ["payload"], postgresql_using="gin")
    op.create_index("ix_document_payload_gin", "document", ["payload"], postgresql_using="gin")


def downgrade() -> None:
    op.drop_index("ix_document_legislature", table_name="document")
    op.drop_index("ix_organe_code_type", table_name="organe")
    op.drop_index("ix_document_payload_gin", table_name="document")
    op.drop_index("ix_organe_payload_gin", table_name="organe")
    op.drop_index("ix_acteur_payload_gin", table_name="acteur")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organe')
    op.drop_table('document')
    op.drop_table('acteur')
    # ### end Alembic commands ###
