"""add generic GIN indexes on payload for organe & document

Revision ID: 2a3f1f080d30
Revises: 05231df2c956
Create Date: 2025-10-03 20:03:59.006375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3f1f080d30'
down_revision: Union[str, None] = '05231df2c956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acteur', sa.Column('organe_refs_jsonb', postgresql.JSONB(astext_type=sa.Text()), sa.Computed("jsonb_path_query_array(payload, '$.**.organeRef')", persisted=True), nullable=False))
    op.create_index('ix_acteur_organe_refs_gin', 'acteur', ['organe_refs_jsonb'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acteur_organe_refs_gin', table_name='acteur', postgresql_using='gin')
    op.drop_column('acteur', 'organe_refs_jsonb')
    # ### end Alembic commands ###
