"""init bdd

Revision ID: a0e7bfaa3000
Revises: 
Create Date: 2025-10-16 19:31:39.127218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0e7bfaa3000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acteur',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('civilite', sa.String(length=10), nullable=True),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('ville_naissance', sa.String(length=255), nullable=True),
    sa.Column('departement_naissance', sa.String(length=255), nullable=True),
    sa.Column('pays_naissance', sa.String(length=255), nullable=True),
    sa.Column('date_deces', sa.Date(), nullable=True),
    sa.Column('profession_libelle', sa.Text(), nullable=True),
    sa.Column('categorie_socio_professionnelle', sa.String(length=255), nullable=True),
    sa.Column('famille_socio_professionnelle', sa.String(length=255), nullable=True),
    sa.Column('url_fiche_acteur', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_acteur_nom', 'acteur', ['nom'], unique=False)
    op.create_index('ix_acteur_prenom', 'acteur', ['prenom'], unique=False)
    op.create_table('document',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('legislature', sa.String(length=50), nullable=True),
    sa.Column('titre_principal', sa.Text(), nullable=True),
    sa.Column('titre_principal_court', sa.Text(), nullable=True),
    sa.Column('denomination_structurelle', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('notice_num_notice', sa.String(length=255), nullable=True),
    sa.Column('notice_formule', sa.Text(), nullable=True),
    sa.Column('notice_adoption_conforme', sa.Text(), nullable=True),
    sa.Column('classification_famille_depot_code', sa.String(length=50), nullable=True),
    sa.Column('classification_famille_depot_libelle', sa.Text(), nullable=True),
    sa.Column('classification_famille_classe_code', sa.String(length=50), nullable=True),
    sa.Column('classification_famille_classe_libelle', sa.Text(), nullable=True),
    sa.Column('classification_famille_espece_code', sa.String(length=50), nullable=True),
    sa.Column('classification_famille_espece_libelle', sa.Text(), nullable=True),
    sa.Column('classification_famille_espece_libelle_edition', sa.Text(), nullable=True),
    sa.Column('classification_type_code', sa.String(length=50), nullable=True),
    sa.Column('classification_type_libelle', sa.Text(), nullable=True),
    sa.Column('classification_sous_type_code', sa.String(length=50), nullable=True),
    sa.Column('classification_sous_type_libelle', sa.Text(), nullable=True),
    sa.Column('classification_sous_type_libelle_edition', sa.Text(), nullable=True),
    sa.Column('classification_statut_adoption', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_depot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_publication', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_publication_web', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organes_referents', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('dossier_ref', sa.String(length=255), nullable=True),
    sa.Column('redacteur', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_document_date_creation', 'document', ['date_creation'], unique=False)
    op.create_index('ix_document_date_depot', 'document', ['date_depot'], unique=False)
    op.create_index('ix_document_date_publication', 'document', ['date_publication'], unique=False)
    op.create_table('organe',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=True),
    sa.Column('libelle', sa.Text(), nullable=True),
    sa.Column('libelle_edition', sa.Text(), nullable=True),
    sa.Column('libelle_abrege', sa.Text(), nullable=True),
    sa.Column('libelle_abrev', sa.String(length=255), nullable=True),
    sa.Column('organe_parent', sa.String(length=255), nullable=True),
    sa.Column('preseance', sa.String(length=50), nullable=True),
    sa.Column('organe_precedent_ref', sa.String(length=255), nullable=True),
    sa.Column('vimode_date_debut', sa.Date(), nullable=True),
    sa.Column('vimode_date_agrement', sa.Date(), nullable=True),
    sa.Column('vimode_date_fin', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_organe_code_type', 'organe', ['code_type'], unique=False)
    op.create_index('ix_organe_libelle', 'organe', ['libelle'], unique=False)
    op.create_table('document_acteur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_uid', sa.String(), nullable=False),
    sa.Column('acteur_uid', sa.String(), nullable=True),
    sa.Column('acteur_ref', sa.String(length=255), nullable=True),
    sa.Column('qualite', sa.String(length=255), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acteur_uid'], ['acteur.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_uid'], ['document.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_acteur_acteur_uid', 'document_acteur', ['acteur_uid'], unique=False)
    op.create_index('ix_document_acteur_document_uid', 'document_acteur', ['document_uid'], unique=False)
    op.create_table('mandat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('acteur_uid', sa.String(), nullable=False),
    sa.Column('organe_uid', sa.String(), nullable=True),
    sa.Column('legislature', sa.String(length=50), nullable=True),
    sa.Column('type_organe', sa.String(length=50), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('preseance', sa.String(length=50), nullable=True),
    sa.Column('nomin_principale', sa.String(length=255), nullable=True),
    sa.Column('infos_qualite_code', sa.String(length=255), nullable=True),
    sa.Column('infos_qualite_libelle', sa.Text(), nullable=True),
    sa.Column('infos_qualite_libelle_sexe', sa.Text(), nullable=True),
    sa.Column('chambre', sa.String(length=50), nullable=True),
    sa.Column('cause_mandat', sa.String(length=255), nullable=True),
    sa.Column('ref_circonscription', sa.String(length=255), nullable=True),
    sa.Column('lieu_region', sa.String(length=255), nullable=True),
    sa.Column('lieu_region_type', sa.String(length=50), nullable=True),
    sa.Column('lieu_departement', sa.String(length=255), nullable=True),
    sa.Column('lieu_num_departement', sa.String(length=10), nullable=True),
    sa.Column('lieu_num_circonscription', sa.String(length=10), nullable=True),
    sa.Column('mandature_date_prise_fonction', sa.Date(), nullable=True),
    sa.Column('mandature_cause_fin', sa.String(length=255), nullable=True),
    sa.Column('mandature_premiere_election', sa.String(length=255), nullable=True),
    sa.Column('mandature_place_hemicycle', sa.String(length=50), nullable=True),
    sa.Column('mandature_mandat_remplace_ref', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acteur_uid'], ['acteur.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organe_uid'], ['organe.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index('ix_mandat_acteur_uid', 'mandat', ['acteur_uid'], unique=False)
    op.create_index('ix_mandat_legislature', 'mandat', ['legislature'], unique=False)
    op.create_index('ix_mandat_organe_uid', 'mandat', ['organe_uid'], unique=False)
    op.create_table('collaborateur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mandat_id', sa.Integer(), nullable=False),
    sa.Column('qualite', sa.String(length=255), nullable=True),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mandat_id'], ['mandat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppleant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mandat_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('suppleant_uid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mandat_id'], ['mandat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppleant')
    op.drop_table('collaborateur')
    op.drop_index('ix_mandat_organe_uid', table_name='mandat')
    op.drop_index('ix_mandat_legislature', table_name='mandat')
    op.drop_index('ix_mandat_acteur_uid', table_name='mandat')
    op.drop_table('mandat')
    op.drop_index('ix_document_acteur_document_uid', table_name='document_acteur')
    op.drop_index('ix_document_acteur_acteur_uid', table_name='document_acteur')
    op.drop_table('document_acteur')
    op.drop_index('ix_organe_libelle', table_name='organe')
    op.drop_index('ix_organe_code_type', table_name='organe')
    op.drop_table('organe')
    op.drop_index('ix_document_date_publication', table_name='document')
    op.drop_index('ix_document_date_depot', table_name='document')
    op.drop_index('ix_document_date_creation', table_name='document')
    op.drop_table('document')
    op.drop_index('ix_acteur_prenom', table_name='acteur')
    op.drop_index('ix_acteur_nom', table_name='acteur')
    op.drop_table('acteur')
    # ### end Alembic commands ###
