"""new table Organe

Revision ID: e1762abdd751
Revises: 2a3f1f080d30
Create Date: 2025-10-14 19:24:41.019755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1762abdd751'
down_revision: Union[str, None] = '2a3f1f080d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organev2',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=True),
    sa.Column('libelle', sa.Text(), nullable=True),
    sa.Column('libelle_edition', sa.Text(), nullable=True),
    sa.Column('libelle_abrege', sa.Text(), nullable=True),
    sa.Column('libelle_abrev', sa.String(length=255), nullable=True),
    sa.Column('organe_parent', sa.String(length=255), nullable=True),
    sa.Column('preseance', sa.String(length=50), nullable=True),
    sa.Column('organe_precedent_ref', sa.String(length=255), nullable=True),
    sa.Column('vimode_date_debut', sa.Date(), nullable=True),
    sa.Column('vimode_date_agrement', sa.Date(), nullable=True),
    sa.Column('vimode_date_fin', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_organe_code_type', 'organev2', ['code_type'], unique=False)
    op.create_index('ix_organe_libelle', 'organev2', ['libelle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organe_libelle', table_name='organev2')
    op.drop_index('ix_organe_code_type', table_name='organev2')
    op.drop_table('organev2')
    # ### end Alembic commands ###
